/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.3/userguide/java_library_plugin.html
 */
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import java.util.UUID

plugins {
	kotlin("jvm")
	application
	id("com.gradleup.shadow")
	id("com.github.gmazzo.buildconfig")
}

kotlin {
	// Legacy receiver/JNA carrier is reference-only after the recorded migration gates passed.
	sourceSets.getByName("main").kotlin.exclude("dev/monaka/tracking/pico/**")
	sourceSets.getByName("test").kotlin.exclude("dev/monaka/tracking/pico/**")
	jvmToolchain {
		languageVersion.set(JavaLanguageVersion.of(17))
	}
}
java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(17))
	}
}
tasks.withType<KotlinCompile> {
	compilerOptions {
		jvmTarget.set(JvmTarget.JVM_17)
		freeCompilerArgs.set(listOf("-Xvalue-classes"))
	}
}

// Set compiler to use UTF-8
tasks.withType<JavaCompile> {
	options.encoding = "UTF-8"
}
tasks.withType<Test> {
	systemProperty("file.encoding", "UTF-8")
	systemProperty("monaka.fixtures", rootProject.file("third_party/monaka-protocol-v2/fixtures").absolutePath)
	doFirst { systemProperty("monaka.test.classpath", sourceSets["test"].runtimeClasspath.asPath) }
	useJUnitPlatform()
}
tasks.withType<Javadoc> {
	options.encoding = "UTF-8"
}

allprojects {
	repositories {
		// Use jcenter for resolving dependencies.
		// You can declare any Maven/Ivy/file repository here.
		mavenCentral()
		maven(url = "https://jitpack.io")
		maven(url = "https://oss.sonatype.org/content/repositories/snapshots")
	}
}

dependencies {
	implementation(project(":server:core"))
	implementation(project(":solarxr-protocol"))

	implementation("commons-cli:commons-cli:1.11.0")
	implementation("org.apache.commons:commons-lang3:3.20.0")
	implementation("com.google.protobuf:protobuf-java:4.31.1")
	implementation("net.java.dev.jna:jna:5.+")
	implementation("net.java.dev.jna:jna-platform:5.+")
	implementation("com.fazecast:jSerialComm:2.11.3") {
		exclude(group = "com.fazecast", module = "android")
	}
	implementation("org.hid4java:hid4java:0.8.0")

	testImplementation(kotlin("test"))
	testImplementation(files(rootProject.file("third_party/monaka-protocol-v2/jvm/libs/gson-2.11.0.jar")))
	testImplementation(platform("org.junit:junit-bom:6.0.2"))
	testImplementation("org.junit.jupiter:junit-jupiter")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.shadowJar {
	minimize {
		exclude(dependency("com.fazecast:jSerialComm:.*"))
		exclude(dependency("net.java.dev.jna:.*:.*"))
		exclude(dependency("com.google.flatbuffers:flatbuffers-java:.*"))

		exclude(project(":solarxr-protocol"))
	}
	archiveBaseName.set("slimevr")
	archiveClassifier.set("")
	archiveVersion.set("")
}
application {
	mainClass.set("dev.slimevr.desktop.Main")
}

buildConfig {
	useKotlinOutput { topLevelConstants = true }
	packageName("dev.slimevr.desktop")

	val gitCommitHash = providers.exec {
		commandLine("git", "rev-parse", "--short=8", "HEAD")
	}.standardOutput.asText.get().trim()
	val gitVersionTag = providers.exec {
		commandLine("git", "--no-pager", "tag", "--sort", "-taggerdate", "--points-at", "HEAD")
	}.standardOutput.asText.get().trim()
	val gitIsClean = providers.exec {
		commandLine("git", "status", "--porcelain")
	}.standardOutput.asText.get().trim().isEmpty()
	buildConfigField("String", "GIT_COMMIT_HASH", "\"${gitCommitHash}\"")
	buildConfigField("String", "GIT_VERSION_TAG", "\"${gitVersionTag}\"")
	buildConfigField("boolean", "GIT_CLEAN", gitIsClean.toString())
}

tasks.run<JavaExec> {
	standardInput = System.`in` // this is not working
	args = listOf("run")
}

tasks.register("picoHardwareProbe") {
	group = "verification"
	description = "Explain migration of the archived PICO native probe"
	doLast { throw GradleException("Legacy PICO receiver is reference-only. See docs/codex/task5/migration.md. Hardware: NOT RUN.") }
}
sourceSets.getByName("main").java.exclude("dev/monaka/tracking/pico/**")
sourceSets.getByName("test").java.exclude("dev/monaka/tracking/pico/**")

// Explicit software E2E only: no native driver/runtime, isolated ephemeral loopback ports.
tasks.register<JavaExec>("mtpProcessE2E") {
	group = "verification"
	description = "Separate-process MTP v2 UDP through existing Slime IK and captured protobuf output"
	dependsOn(tasks.testClasses)
	classpath = sourceSets["test"].runtimeClasspath
	mainClass.set("dev.monaka.tracking.desktop.MtpProcessE2E")
	javaLauncher.set(javaToolchains.launcherFor { languageVersion.set(JavaLanguageVersion.of(17)) })
	systemProperty("monaka.fixtures", rootProject.file("third_party/monaka-protocol-v2/fixtures").absolutePath)
	doFirst {
		val output = providers.gradleProperty("monakaE2EOutput").orNull
			?: layout.buildDirectory.dir("mtp-process-e2e/${UUID.randomUUID()}").get().asFile.absolutePath
		args(rootProject.file(output).absolutePath)
	}
}
